<template>
  <nav class="grid grid-cols-2 md:grid-cols-4 gap-y-12 uppercase">
    <div class="space-y-12">
      <div>
        <HeadingSans>
          Brands
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="setetres"
              to="https://setetres.st"
            >
              setetres.st
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="xxxxxxxooo"
              to="https://xxxxxxx.ooo"
            >
              xxxxxxx.ooo
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="mortelenta"
              to="https://mortelenta.org"
            >
              mortelenta.org
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="mortelenta"
              to="https://rasgado.net"
            >
              rasgado.net
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="hashima"
              to="https://hashima.gg"
            >
              hashima.gg
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="powwws"
              to="https://poww.ws"
            >
              poww.ws
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-blue-500"
              external="true"
              id="creepycrappyshow"
              to="https://creepycrappy.show"
            >
              creepycrappy.show
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>
